# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Siddharth Saha
description: >- # this means to ignore newlines until "baseurl:"
  Siddharth's minimal blog page.
# baseurl: "/bay" # the subpath of the site
url: "https://trunc8.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-193570686-1"

permalink: /:year/:month/:day/:title


# Build settings
timezone: Asia/Kolkata
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1


