- title: ROS2 RADI and Amazon warehouse exercise
  image:
    src: /assets/img/project/amazon-single-slam.gif
    alt: 
  description: Done as part of my Google Summer of Code project at JdeRobot
  links:
    repo: https://github.com/TheRoboticsClub/gsoc2021-Siddharth_Saha
    demo: https://youtu.be/RfW2hI_8j74
    blog: https://theroboticsclub.github.io/gsoc2021-Siddharth_Saha/milestones/2021/08/21/final-report

- title: Mapping Regions of Dynamic Activity & Building Dynamic-free 3D Occupancy Maps
  image:
    src: /assets/img/project/dynamic-octomap.png
    alt: 
  description: As part of my Bachelor's Thesis, I designed & implemented a novel clustering algorithm in ROS OctoMap to reject nodes with high dynamic activity
  links:
    repo: https://github.com/trunc8/Dynamic-Octomap
    demo: https://youtu.be/rUUqPmobm1k

- title: Quadruped Robot
  image:
    src: /assets/img/project/stride.png
    alt: 
  description: Founding member of an institute technical team to solve the international urban search and rescue challenge - RoboCup Rescue League

- title: Two-wheeled Self-Balancing Bot
  image:
    src: /assets/img/project/self-balancing-bot.jpg
    alt: 
  description: Demonstrates the inverted pendulum problem using a two-wheeled bot and input from gyroscope+accelerometer module
  links:
    demo: https://youtu.be/zCnvgg1dpSY
    blog: https://trunc8.github.io/2020/12/15/doc-self-balancing-bot

- title: Autonomous Drone Exploration
  image:
    src: /assets/img/project/interiit.png
    alt: 
  description: (Team leader in *Inter IIT Tech Meet '21* ) Quadrotor simulation capable of navigating in a complex static environment by avoiding on-field obstacle-collision and reaching the target destination after its correct detection. 
  links:
    repo: https://github.com/trunc8/drdo-drone-challenge

- title: Multi-robot Capture of Non-adversarial Target
  image:
    src: /assets/img/project/mespp.png
    alt: 
  description: Capture of a moving target using Mixed Integer Linear Programming. Implementation from scratch of 'MILP Models for Multi-Robot Non-Adversarial Search' paper
  links:
    repo: https://github.com/trunc8/multirobot-efficient-search-path-planning
    blog: https://trunc8.github.io/2021/04/01/pr-mespp

- title: International Micromouse Challenge
  image:
    src: /assets/img/project/comp-imc.png
    alt: 
  description: Reach from the corner square to the center of an unknown maze in the shortest time
  links:
    repo: https://github.com/trunc8/international-micromouse-techfest2020
    demo: https://youtu.be/PcbNQ-tVwQw?t=107
    blog: https://trunc8.github.io/2020/12/28/comp-imc

- title: Automated Graph Reader
  image:
    src: /assets/img/project/auto-graph-reader-demo.png
    alt: 
  description: Deployed live on Heroku server, the web-app accepts queries for y-values in simple input graphs. The solution is based on image processing, OCR, and a lot of algorithm design
  links:
    repo: https://github.com/trunc8/auto-graph-reader-webapp

- title: Optimization of vehicle suspension
  image:
    src: /assets/img/project/suspension.png
    alt: 
  description: Comparison of standard library functions and our own implementations of genetic algorithm, simulated annealing, and particle swarm optimization for the vehicle suspension optimization
  links:
    repo: https://github.com/trunc8/optimization-project

- title: Snippet-to-text Extraction
  image:
    src: /assets/img/project/snippet-to-text-demo.png
    alt: 
  description: Deployed live on Heroku server, the web-app allows you to read image snippets as continuous text
  links:
    repo: https://github.com/trunc8/snippet-to-text-webapp

- title: Panoramic Mosaicing
  image:
    src: /assets/img/project/panorama.jpg
    alt: 
  description: Uses ORB feature extractor, Brute Force Matcher with Hamming Norm, and RANSAC algorithm to mosaic any number of input images
  links:
    repo: https://github.com/trunc8/panoramic-mosaicing

- title: Image Quilting
  image:
    src: /assets/img/project/image-quilting.png
    alt: 
  description: This achieves *Texture Transfer* using simple memoization-based Image Quilting technique (where people are nowadays using deep learning techniques). The *Texture Synthesis* implementation is useful for creating background in video games with cheap computation
  links:
    repo: https://github.com/trunc8/image-quilting

- title: Sudoku Solver Using Block Printing
  image:
    src: /assets/img/project/sudoku-block-printer.png
    alt: 
  description: Implemented a Raspian-based automated Machine to physically fill into any given unsolved Sudoku grid using computer-vision
  links:
    repo: https://github.com/trunc8/sudoku-solver-itsp-2018
    demo: https://youtu.be/3ukm6GfWYAw

- title: Ball Tracking using OpenCV and ROS
  image:
    src: /assets/img/project/ball-tracking.png
    alt: 
  description: Python implementation of Ball tracking using OpenCV and CvBridge in ROS1
  links:
    repo: https://github.com/trunc8/ball-tracking-opencv-and-ros
    demo: https://youtu.be/zst5iFkaByQ

- title: Ricart-Agrawala Algorithm
  image:
    src: /assets/img/project/ricart-agrawal.png
    alt: 
  description: Implementation of mutual exclusion in computer networks. The Ricart-Agrawala algorithm provides an optimal solution to the problem of mutually exclusive access to a critical section in computer networks, whose nodes communicate only by messages and do not share memory
  links:
    repo: https://github.com/trunc8/ricart-agrawala-algorithm

- title: Wifi De-auth Attacker
  image:
    src: /assets/img/project/esp8266.jpg
    alt: 
  description: Programmed ESP8266 (Wi-Fi microchip) to spoof an access point and send de-authentication frames, exploiting vulnerability in IEEE 802.11 standards of the absence of encryption for management frames

- title: Gyro Brick Breaker
  image:
    src: /assets/img/project/gyro-brick-breaker.jpg
    alt: 
  description: Led 5-membered team to develop a hand-gesture controlled brick-breaking game coded in Processing IDE. One among 3 projects showcased at the Undergraduate Freshmen Technical Orientation 2018

- title: Conway’s Game of Life
  image:
    src: /assets/img/project/conway.png
    alt: 
  description: Terminal based version of the hacker's favorite game. The source code is accompanied with unittesting. Developed as part of JdeRobot's GSoC Python Challenge
  links:
    repo: https://github.com/trunc8/conways-game-of-life

- title: Labyrinth CMake app
  image:
    src: /assets/img/project/labyrinth.png
    alt: 
  description: CMakeLists based app to find the longest route in a text map. Developed as part of JdeRobot's GSoC C++ Challenge
  links:
    repo: https://github.com/trunc8/labyrinth-cmake-app
